### https://docs.juliacn.com/latest/manual/functions/#destructuring-assignment
+ pack类数据, 都能unpack,
+ 但Tuple在函数的参数传递和结果返回中常用
+ 先测试Tuple,再测试其他类型

In [2]:
(a,b,c) = 1:3
b

2

In [4]:
function foo(a,b)
    a+b, a*b
end
fs = foo(2,3)

(5, 6)

In [5]:
f1, f2 = foo(2,3)

(5, 6)

In [6]:
f1

5

In [6]:
f2, f1 = f1, f2 # 交换
f1

6

In [8]:
f1, f2, f3 = foo(2,3)

BoundsError: BoundsError: attempt to access Tuple{Int64, Int64} at index [3]

In [10]:
t1, t2 = (5,7)
t2

7

In [12]:
t1, t2 = (5,6, 7)
t1 |> display
t2 |> display

5

6

In [13]:
t1, t2, t3, t4 = (5,6, 7)

BoundsError: BoundsError: attempt to access Tuple{Int64, Int64, Int64} at index [4]

In [14]:
v1, v2 = [5,6, 7]
v1 |> display
v2 |> display

5

6

In [1]:
_, _, _, d = 1:10
d

4

In [7]:
X = zeros(3)
X |> display

X[1], (a,b) = [1, (2, 3)]

X |> display
a |> display
b |> display

3-element Vector{Float64}:
 0.0
 0.0
 0.0

3-element Vector{Float64}:
 1.0
 0.0
 0.0

2

3

### ... 可变变量 (known as *slurping*)
https://docs.julialang.org/en/v1/manual/functions/#destructuring-assignment


In [12]:
s1, s2... = "hello"
s1 |> display
s2 |> display

'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)

"ello"

  **help?> abs2**<br>  
  Squared absolute value of x.
  ```julia
  julia> abs2(-3)
  9  
  julia> abs2(3.0 + 4.0im)
  25.0
  ```

In [15]:
abs2_1, abs2_2... = Iterators.map(abs2, 1:4)
abs2_2

Base.Iterators.Rest{Base.Generator{UnitRange{Int64}, typeof(abs2)}, Int64}(Base.Generator{UnitRange{Int64}, typeof(abs2)}(abs2, 1:4), 1)

In [16]:
for i in abs2_2
    println(i)
end

4
9
16


In [20]:
a2, b2..., c2 = 1:5
a2 |> display
b2 |> display
c2 |> display

1

3-element Vector{Int64}:
 2
 3
 4

5

In [21]:
front..., tail = "Hi!"
front |> display
tail |> display

"Hi"

'!': ASCII/Unicode U+0021 (category Po: Punctuation, other)

https://docs.julialang.org/en/v1/manual/functions/#Property-destructuring

Instead of destructuring based on iteration, the right side of assignments can also be destructured using property names. This follows the syntax for `NamedTuples`, and works by assigning to each variable on the left a property of the right side of the assignment with the same name using getproperty:<br>

与基于迭代的解构不同，赋值的右侧也可以使用属性名进行解构。这遵循`NamedTuples`的语法，并通过使用 `getproperty` 将赋值右侧的相同名称的属性赋值给左侧的每个变量来工作：

In [1]:
(; b, a) = (a=1, b=2, c=3)

(a=1, b=2, c=3) |> typeof |> display
propertynames((a=1, b=2, c=3)) |> display

a |> display
c |> display

@NamedTuple{a::Int64, b::Int64, c::Int64}

(:a, :b, :c)

1

UndefVarError: UndefVarError: `c` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [29]:
(b, a) = (a=1, b=2, c=3)  # 去掉分号不对
a |> display
b |> display

2

1